# Generated by Django 3.0.5 on 2020-05-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='date_del',
            field=models.DateField(blank=True, null=True),
        ),
    ]
